#!/usr/bin/env python3
"""
serve_map.py — Minimal static server for the D3 map (docs/index.html,
docs/markdown_style.html). Both files are self-contained (data embedded),
generated by scripts/6_sqlite_to_web.py — no backend logic needed here.

Run: python3 serve_map.py
Open: http://localhost:8766
"""
import os
from pathlib import Path
from flask import Flask, send_from_directory, abort

app = Flask(__name__)

BASE_DIR = Path(__file__).parent
DOCS_DIR = BASE_DIR / 'docs'


@app.route('/', defaults={'path': 'index.html'})
@app.route('/<path:path>')
def serve_static(path):
    file_path = DOCS_DIR / path
    if not file_path.exists() or not file_path.is_file():
        abort(404)
    return send_from_directory(str(DOCS_DIR), path)


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8766))
    host = os.environ.get('HOST', '0.0.0.0')
    app.run(host=host, port=port, threaded=True)
